language: php
dist: trusty
sudo: false
php:
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm # on Trusty only
    - nightly
script: "make test"
before_install: "composer install --dev"
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
