# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DriverApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for DriverApp

  pod 'GoogleMaps'
  pod "RMDateSelectionViewController", "~> 2.0.3"
  pod 'Stripe'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'PubNub'
  pod 'FBSDKCoreKit', "~> 4.15.1"
  pod 'FBSDKLoginKit', "~> 4.15.1"
  pod 'IQKeyboardManager'
  pod 'SDWebImage', '~>3.8'
  pod 'DGActivityIndicatorView'
  pod 'GoogleSignIn'
  pod 'Fabric'
  pod 'TwitterCore', "~> 3.0.3"
  pod 'TwitterKit', "~> 3.2.2"
  pod 'SplunkMint'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Google-Maps-iOS-Utils', :git => "https://github.com/googlemaps/google-maps-ios-utils", :branch => 'master'

  target 'DriverAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DriverAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
